### PR TITLE
Annotate Pull Request

### PR DESCRIPTION
**Pull request by kchason**
- Adds support for annotating pull requests with validation results
- Bumps `Dockerfile` reference to `1.4`
- Bumps action reference to `v2.8.0`

### CODE REVIEW

**Comment by kchason** [comment]
${COMMENT_BODY}

**Comment by kchason** [comment]
TEST COMMENT: <table><tr><th>File</th><th>Result</th></tr><tr><td>test/valid/valid_case.yaml</td><td>Passed</td></tr><tr><td>test/invalid/invalid_case.yaml</td><td>Failed</td></tr></table>

**Comment by kchason** [comment]
TEST COMMENT:<br /><br />-------<br /> <h3>CASE Validation Passed <span style='color=#060;'>&#x2713;</span></h3> <table><tr><th>File</th><th>Result</th></tr><tr><td>test/valid/valid_case.yaml</td><td>Passed</td></tr><tr><td>test/invalid/invalid_case.yaml</td><td>Failed</td></tr></table>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>simple-case.jsonld</td><td><span>&#x2717;</span></td></tr><tr><td>invalid.json</td><td><span>&#x2713;</span></td></tr></table><h2>Details</h2><details><summary><h3>simple-case.jsonld <span>&#x2717;</span></h3></summary>Validation Report<br />Conforms: False<br />Results (3):<br />Validation Result in SPARQLConstraintComponent (http://www.w3.org/ns/shacl#SPARQLConstraintComponent):<br />	Severity: sh:Info<br />	Source Shape: core:UcoThing-identifier-regex-shape<br />	Focus Node: kb:investigative-action-1<br />	Value Node: kb:investigative-action-1<br />	Source Constraint: [ rdf:type sh:SPARQLConstraint ; rdfs:seeAlso <https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.3> ; sh:message Literal("UcoThings are suggested to end with a UUID.", lang=en) ; sh:select Literal("<br />			PREFIX uco-core: <https://ontology.unifiedcyberontology.org/uco/core/><br />			SELECT $this<br />			WHERE {<br />			        $this a/rdfs:subClassOf* uco-core:UcoThing .<br />			        FILTER (<br />			                ! REGEX (<br />			                        STR($this),<br />			                        "[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}$",<br />			                        "i"<br />			                )<br />			        )<br />			}<br />		") ]<br />	Message: UcoThings are suggested to end with a UUID.<br />Validation Result in SPARQLConstraintComponent (http://www.w3.org/ns/shacl#SPARQLConstraintComponent):<br />	Severity: sh:Info<br />	Source Shape: core:UcoThing-identifier-regex-shape<br />	Focus Node: kb:abc-org-1<br />	Value Node: kb:abc-org-1<br />	Source Constraint: [ rdf:type sh:SPARQLConstraint ; rdfs:seeAlso <https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.3> ; sh:message Literal("UcoThings are suggested to end with a UUID.", lang=en) ; sh:select Literal("<br />			PREFIX uco-core: <https://ontology.unifiedcyberontology.org/uco/core/><br />			SELECT $this<br />			WHERE {<br />			        $this a/rdfs:subClassOf* uco-core:UcoThing .<br />			        FILTER (<br />			                ! REGEX (<br />			                        STR($this),<br />			                        "[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}$",<br />			                        "i"<br />			                )<br />			        )<br />			}<br />		") ]<br />	Message: UcoThings are suggested to end with a UUID.<br />Validation Result in SPARQLConstraintComponent (http://www.w3.org/ns/shacl#SPARQLConstraintComponent):<br />	Severity: sh:Info<br />	Source Shape: core:UcoThing-identifier-regex-shape<br />	Focus Node: kb:123-tool-1<br />	Value Node: kb:123-tool-1<br />	Source Constraint: [ rdf:type sh:SPARQLConstraint ; rdfs:seeAlso <https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.3> ; sh:message Literal("UcoThings are suggested to end with a UUID.", lang=en) ; sh:select Literal("<br />			PREFIX uco-core: <https://ontology.unifiedcyberontology.org/uco/core/><br />			SELECT $this<br />			WHERE {<br />			        $this a/rdfs:subClassOf* uco-core:UcoThing .<br />			        FILTER (<br />			                ! REGEX (<br />			                        STR($this),<br />			                        "[0-9a-f]{8}-[0-9a-f]{4}-[0-5][0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}$",<br />			                        "i"<br />			                )<br />			        )<br />			}<br />		") ]<br />	Message: UcoThings are suggested to end with a UUID.<br /></details><details><summary><h3>invalid.json <span>&#x2713;</span></h3></summary>Validation Report<br />Conforms: True<br /></details>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>simple-case.jsonld</td><td><span>&#x2717;</span></td></tr><tr><td>no-context.json</td><td><span>&#x2717;</span></td></tr><tr><td>space file.json</td><td><span>&#x2717;</span></td></tr></table><h2>Details</h2><details><summary><h3>simple-case.jsonld <span>&#x2717;</span></h3></summary><pre></pre></details><details><summary><h3>no-context.json <span>&#x2717;</span></h3></summary><pre></pre></details><details><summary><h3>space file.json <span>&#x2717;</span></h3></summary><pre></pre></details>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>simple-case.jsonld</td><td><span>&#x2713;</span></td></tr><tr><td>no-context.json</td><td><span>&#x2713;</span></td></tr><tr><td>space file.json</td><td><span>&#x2713;</span></td></tr></table><h2>Details</h2><details><summary><h3>simple-case.jsonld <span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>no-context.json <span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>space file.json <span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>simple-case.jsonld</td><td><span>&#x2713;</span></td></tr><tr><td>no-context.json</td><td><span>&#x2713;</span></td></tr><tr><td>space file.json</td><td><span>&#x2713;</span></td></tr></table><h2>Details</h2><details><summary><h3>simple-case.jsonld <span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>no-context.json <span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>space file.json <span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr></table><h2>Details</h2>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>tests/data/no-context.json</td><td><span>&#x2713;</span></td></tr><tr><td>tests/data/simple-case.jsonld</td><td><span>&#x2713;</span></td></tr><tr><td>tests/data/space file.json</td><td><span>&#x2713;</span></td></tr></table><h2>Details</h2><details><summary><h3>tests/data/no-context.json&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>tests/data/simple-case.jsonld&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>tests/data/space file.json&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>tests/data/no-context.json</td><td><span>&#x2713;</span></td></tr><tr><td>tests/data/simple-case.jsonld</td><td><span>&#x2713;</span></td></tr><tr><td>tests/data/space file.json</td><td><span>&#x2713;</span></td></tr></table><h2>Details</h2><details><summary><h3>tests/data/no-context.json&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>tests/data/simple-case.jsonld&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>tests/data/space file.json&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details>

**Comment by kchason** [comment]
<h1>CASE Validation Results</h1><h2>Summary</h2><table><tr><th>File</th><th>Valid</th></tr><tr><td>tests/data/no-context.json</td><td><span>&#x2713;</span></td></tr><tr><td>tests/data/simple-case.jsonld</td><td><span>&#x2713;</span></td></tr><tr><td>tests/data/space file.json</td><td><span>&#x2713;</span></td></tr></table><h2>Details</h2><details><summary><h3>tests/data/no-context.json&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>tests/data/simple-case.jsonld&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details><details><summary><h3>tests/data/space file.json&nbsp;<span>&#x2713;</span></h3></summary><pre>Validation Report
Conforms: True
</pre></details>

**Review by ajnelson-nist — APPROVED** [review]

**Pull request merged**
